name: Manual
description: Create book manuals
author: StarTux
version: 0.1
api-version: 1.13
main: com.winthier.manual.ManualPlugin
depend: [ Custom ]
softdepend: []
commands:
  manual:
    aliases: [man]
    description: manual
    permission: manual.manual
    usage: |-
      /manual give <manual> [player] - Spawn a manual
      /manual list - List loaded manuals
      /manual reload - Reload manuals
      /manual info - Info about manual in hand
      /manual reloadhand - Reload and force update manual in hand
      /manual url <url> - Generate manual from URL
permissions:
  manual.manual:
    description: use /manual
    default: op
